name: frontend
description: "Flutter client for the Spiritual Q&A Platform."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  dio: any
  envied: any
  flutter:
    sdk: flutter
  flutter_riverpod: any
  flutter_secure_storage: any
  freezed_annotation: any
  go_router: any
  google_fonts: any
  logger: any
  lucide_flutter: any
  riverpod_annotation: any
  flutter_animate: any
  marionette_flutter: ^0.4.0
  flutter_markdown: any
  url_launcher: any
  path_provider: any
  freerasp: any
  secure_application: any
  share_plus: any
  http_certificate_pinning: any
  cryptography: any
  shared_preferences: any
  cupertino_icons: any
  file_picker: ^10.3.10
  marionette_logger: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  riverpod_generator: any
  freezed: any
  json_serializable: any
  flutter_gen_runner: any
  envied_generator: any
  mocktail: ^1.0.4
  accessibility_tools: any

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/gen/
  line_length: 80
