project-includes = ["app", "tests", "scripts"]
search-path = ["/workspaces/cs698-repo/backend"]
site-package-path = ["/workspaces/cs698-repo/backend/.venv/lib/python3.11/site-packages"]
python-interpreter-path = "/workspaces/cs698-repo/backend/.venv/bin/python3"
python-version = "3.11"
