import 'dart:math';
import 'package:cryptography/cryptography.dart';

/// Service to handle account recovery key generation and mnemonic encoding.
///
/// Uses a 256-word dictionary to encode a 128-bit (16-byte) random recovery key
/// into a 16-word mnemonic phrase (8 bits per word).
class RecoveryService {
  final _random = Random.secure();

  /// Dictionary of 256 common, distinct, short English words.
  /// Each word represents 8 bits (1 byte) of entropy.
  static const List<String> _wordList = [
    'abandon',
    'ability',
    'able',
    'about',
    'above',
    'absent',
    'absorb',
    'abstract',
    'absurd',
    'abuse',
    'access',
    'accident',
    'account',
    'accuse',
    'achieve',
    'acid',
    'acoustic',
    'acquire',
    'across',
    'act',
    'action',
    'actor',
    'actress',
    'actual',
    'adapt',
    'add',
    'addict',
    'address',
    'adjust',
    'admit',
    'adult',
    'advance',
    'advice',
    'aerobic',
    'affair',
    'afford',
    'afraid',
    'again',
    'age',
    'agent',
    'agree',
    'ahead',
    'aim',
    'air',
    'airport',
    'aisle',
    'alarm',
    'album',
    'alcohol',
    'alert',
    'alien',
    'all',
    'alley',
    'allow',
    'almost',
    'alone',
    'alpha',
    'already',
    'also',
    'alter',
    'always',
    'amaze',
    'ambush',
    'amount',
    'amuse',
    'analyst',
    'anchor',
    'ancient',
    'anger',
    'angle',
    'angry',
    'animal',
    'ankle',
    'announce',
    'annual',
    'another',
    'answer',
    'antenna',
    'antique',
    'anxiety',
    'any',
    'apart',
    'apology',
    'appear',
    'apple',
    'approve',
    'april',
    'arch',
    'arctic',
    'area',
    'arena',
    'argue',
    'arm',
    'armed',
    'armor',
    'army',
    'around',
    'arrange',
    'arrest',
    'arrive',
    'arrow',
    'art',
    'artefact',
    'artist',
    'artwork',
    'ask',
    'aspect',
    'assault',
    'asset',
    'assist',
    'assume',
    'asthma',
    'athlete',
    'atom',
    'attack',
    'attend',
    'attitude',
    'attract',
    'auction',
    'audit',
    'august',
    'aunt',
    'author',
    'auto',
    'autumn',
    'average',
    'avocado',
    'avoid',
    'awake',
    'aware',
    'away',
    'awesome',
    'awful',
    'awkward',
    'axis',
    'baby',
    'bachelor',
    'bacon',
    'badge',
    'bag',
    'balance',
    'balcony',
    'ball',
    'bamboo',
    'banana',
    'banner',
    'bar',
    'barely',
    'bargain',
    'barrel',
    'base',
    'basic',
    'basket',
    'battle',
    'beach',
    'beam',
    'bean',
    'beauty',
    'because',
    'become',
    'beef',
    'before',
    'begin',
    'behave',
    'behind',
    'believe',
    'below',
    'belt',
    'bench',
    'benefit',
    'best',
    'betray',
    'better',
    'between',
    'beyond',
    'bicycle',
    'bid',
    'bike',
    'bind',
    'biology',
    'bird',
    'birth',
    'bitter',
    'black',
    'blade',
    'blame',
    'blanket',
    'blast',
    'bleak',
    'bless',
    'blind',
    'blood',
    'blossom',
    'blouse',
    'blue',
    'blur',
    'blush',
    'board',
    'boat',
    'body',
    'boil',
    'bomb',
    'bone',
    'bonus',
    'book',
    'boost',
    'border',
    'boring',
    'borrow',
    'boss',
    'bottom',
    'bounce',
    'box',
    'boy',
    'bracket',
    'brain',
    'brand',
    'brass',
    'brave',
    'bread',
    'breeze',
    'brick',
    'bridge',
    'brief',
    'bright',
    'bring',
    'brisk',
    'broccoli',
    'broken',
    'bronze',
    'broom',
    'brother',
    'brown',
    'brush',
    'bubble',
    'buddy',
    'budget',
    'buffalo',
    'build',
    'bulb',
    'bulk',
    'bullet',
    'bundle',
    'bunker',
    'burden',
    'burger',
    'burst',
    'bus',
    'busy',
    'butterfly',
    'button',
    'buy',
    'buyer',
    'buzz',
    'byte',
    'cab',
  ];

  /// Generates a random 128-bit RecoveryKey (16 bytes).
  Future<SecretKey> generateRecoveryKey() async {
    final bytes = List<int>.generate(16, (_) => _random.nextInt(256));
    return SecretKey(bytes);
  }

  /// Encodes a RecoveryKey (16 bytes) into a 16-word mnemonic phrase.
  String keyToMnemonic(List<int> keyBytes) {
    if (keyBytes.length != 16) {
      throw ArgumentError('Key must be exactly 16 bytes (128 bits)');
    }
    return keyBytes.map((b) => _wordList[b]).join(' ');
  }

  /// Decodes a 16-word mnemonic phrase back into 16 key bytes.
  List<int> mnemonicToKey(String mnemonic) {
    final words = mnemonic.trim().toLowerCase().split(RegExp(r'\s+'));
    if (words.length != 16) {
      throw FormatException('Mnemonic must be exactly 16 words');
    }

    final bytes = <int>[];
    for (final word in words) {
      final index = _wordList.indexOf(word);
      if (index == -1) {
        throw FormatException('Invalid word in mnemonic: $word');
      }
      bytes.add(index);
    }
    return bytes;
  }
}
