import '../constants/env.dart';

/// Centralized configuration for environment-specific variables.
///
/// Wraps the [Env] class generated by `envied` to provide validated,
/// consistent access to configuration keys.
class EnvConfig {
  /// The base URL for the remote API.
  ///
  /// Throws an [AssertionError] if the URL is empty, ensuring that
  /// the app fails fast if the `.env` file is misconfigured.
  static String get apiBaseUrl {
    final baseUrl = Env.apiBaseUrl;
    assert(
      baseUrl.isNotEmpty,
      'API_BASE_URL is not defined in the environment. '
      'Ensure your .env file is correctly set up.',
    );
    return baseUrl;
  }

  /// Whether the app is running in a development/mock-aware environment.
  ///
  /// This can be used to toggle features or logging verbosity.
  static bool get isDevelopment {
    // In a real app, this could be tied to an ENV_VAR or kDebugMode.
    // For now, we provide it as a hook for future logic.
    return true;
  }
}
