name: Deploy to GitHub Pages

on:
  push:
    branches:
      - frontend_development
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Prepare dummy .env
        run: |
          cd frontend
          cp .env.web .env

      - name: Install dependencies
        run: |
          cd frontend
          flutter pub get

      - name: Generate code
        run: |
          cd frontend
          dart run build_runner build --delete-conflicting-outputs

      - name: Build Web
        run: |
          cd frontend
          flutter build web --base-href "/cs698-repo/" --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build/web
